version: '3.5'

services:
  app:
    build: .
    volumes:
      - ./:/app
    working_dir: /app

  webserver:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
